version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    command: npm run dev
    ports:
      - '3000:3000'
    depends_on:
      - database
    networks:
      - app-network
   
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'hr_department'
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
    networks:
      - app-network
   
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    ports:
      - '4200:4200'
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true
   
  client:
    build: ./client
    volumes:
       - ./client:/usr/src/app
       - /usr/src/app/node_modules
    command: npm start
    ports:
      - '8080:8080'
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  app-network:
    driver: bridge

volumes:
  db_data: